export const FETCH_DEPARTURES_LIST = "FETCH_DEPARTURES_LIST";
export const FETCH_DESTINATIONS_LIST = "FETCH_DESTINATIONS_LIST";

export const FETCH_TOURS_LIST = "FETCH_TOURS_LIST";
export const DELETE_TOUR = "DELETE_TOUR";
export const GET_TOUR_ID = "GET_TOUR_ID";





// TOUR
export const SHOW_FORM = "SHOW_FORM";
export const CLOSE_FORM = "CLOSE_FORM";
// FormUpdate ActionType
export const SHOW_FORM_UPDATE = "SHOW_FORM_UPDATE";
export const FETCH_TOUR_UPDATE_INFO = "FETCH_TOUR_UPDATE_INFO";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const SEARCH_TOUR = "SEARCH_TOUR";
export const MIN_PRICE = "MIN_PRICE";
export const MAX_PRICE = "MAX_PRICE";
export const MIN_DISCOUNT = "MIN_DISCOUNT";
export const MAX_DISCOUNT = "MAX_DISCOUNT";
export const MIN_RATTING = "MIN_RATTING";
export const MAX_RATTING = "MAX_RATTING";
export const FIND_TOUR = "FIND_TOUR";
export const SEARCH_DES = "SEARCH_DES";





export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";

// Booking
export const FETCH_BOOKING_LIST = "FETCH_BOOKING_LIST";
export const DELETE_BOOKING = "DELETE_BOOKING";

export const SHOW_FORM_BOOKING_UD = "SHOW_FORM_BOOKING_UD";
export const CLOSE_FORM_BOOKING_UD = "CLOSE_FORM_BOOKING_UD";

export const FETCH_BOOKING_UPDATE_INFO = "FETCH_BOOKING_UPDATE_INFO";
export const SEARCH_BOOKING = "SEARCH_BOOKING";

export const SHOW_FORM_BOOKING_CREATE = "SHOW_FORM_BOOKING_CREATE";
export const CLOSE_FORM_BOOKING_CREATE = "CLOSE_FORM_BOOKING_CREATE";

